const data = {
    products:[
        {
            _id: '1',
            name:'Prototype Slim Shirt',
            category:'shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock: 10,
            brand:'Prototype',
            rating: 4.5,
            numReviews:10,
            description:'High quality product',
        },
        {
            _id: '2',
            name:'Prototype Slim Shirt',
            category:'shirts',
            image:'/images/p2.jpg',
            price:120,
            countInStock: 20,
            brand:'Prototype',
            rating: 4.0,
            numReviews:10,
            description:'High quality product',
        },
        {
            _id: '3',
            name:'Prototype Slim Shirt',
            category:'shirts',
            image:'/images/p3.jpg',
            price:125,
            countInStock: 0,
            brand:'Prototype',
            rating: 4.8,
            numReviews:17,
            description:'High quality product',
        },
        {
            _id: '4',
            name:'Prototype Slim Pants',
            category:'shirts',
            image:'/images/p4.jpg',
            price:100,
            countInStock: 15,
            brand:'Prototype',
            rating: 4.5,
            numReviews:14,
            description:'High quality product',
        },
        {
            _id: '5',
            name:'Prototype Slim Pants',
            category:'shirts',
            image:'/images/p5.jpg',
            price:90,
            countInStock: 5,
            brand:'Prototype',
            rating: 4.5,
            numReviews:18,
            description:'High quality product',
        },
        {
            _id: '6',
            name:'Prototype Slim Pants',
            category:'shirts',
            image:'/images/p6.jpg',
            price:89,
            countInStock: 12,
            brand:'Prototype',
            rating: 4.5,
            numReviews:12,
            description:'High quality product',
        },
    ]
};
export default data;