const data = {
    products:[
        {
            _id: '1',
            name:'Prototype Slim Shirt',
            category:'shirts',
            image:'/images/p1.jpg',
            price:120,
            brand:'Prototype',
            rating: 4.5,
            numReviews:15,
            description:'High quality product',
        },
        {
            _id: '2',
            name:'Prototype Slim Shirt',
            category:'shirts',
            image:'/images/p3.jpg',
            price:120,
            brand:'Prototype',
            rating: 4.5,
            numReviews:19,
            description:'High quality product',
        },
        {
            _id: '3',
            name:'Prototype Slim Shirt',
            category:'shirts',
            image:'/images/p2.jpg',
            price:125,
            brand:'Prototype',
            rating: 4.5,
            numReviews:11,
            description:'High quality product',
        },
        {
            _id: '4',
            name:'Prototype Slim Pants',
            category:'shirts',
            image:'/images/p4.jpg',
            price:100,
            brand:'Prototype',
            rating: 4.5,
            numReviews:16,
            description:'High quality product',
        },
        {
            _id: '5',
            name:'Prototype Slim Pants',
            category:'shirts',
            image:'/images/p5.jpg',
            price:90,
            brand:'Prototype',
            rating: 4.5,
            numReviews:18,
            description:'High quality product',
        },
        {
            _id: '6',
            name:'Prototype Slim Pants',
            category:'shirts',
            image:'/images/p6.jpg',
            price:89,
            brand:'Prototype',
            rating: 4.5,
            numReviews:12,
            description:'High quality product',
        },
    ]
};
export default data;